"""
PR Creator module for creating refactored PRs with quality scores.
"""
from typing import List, Dict, Any, Optional
from src.gh_integration.client import Githubclient
from src.utils.logger import get_logger

logger = get_logger(__name__)


def generate_branch_name(pr_number: int) -> str:
    """
    Generate branch name for refactored code.
    
    Args:
        pr_number: Original PR number
        
    Returns:
        str: Branch name (e.g., "refactored-pr-123")
    """
    return f"refactored-pr-{pr_number}"


def format_score_comparison(
    original_scores: Optional[Dict[str, float]] = None,
    refactored_scores: Optional[Dict[str, float]] = None
) -> str:
    """
    Format score comparison as markdown table.
    
    Args:
        original_scores: Scores before refactoring
        refactored_scores: Scores after refactoring
        
    Returns:
        str: Markdown formatted table
    """
    if not original_scores or not refactored_scores:
        return "**Quality scores will be calculated soon.**"
    
    # Calculate changes
    def get_change(metric: str) -> str:
        orig = original_scores.get(metric, 0)
        refact = refactored_scores.get(metric, 0)
        diff = refact - orig
        
        if diff > 0:
            return f"+{diff:.1f}"
        elif diff < 0:
            return f"{diff:.1f}"
        else:
            return "0.0"
    
    # Build table
    table = """## Quality Score Comparison

| Metric | Before | After | Change |
|--------|--------|-------|--------|
"""
    
    metrics = ["overall", "bleu", "complexity", "maintainability"]
    for metric in metrics:
        orig = original_scores.get(metric, 0)
        refact = refactored_scores.get(metric, 0)
        change = get_change(metric)
        
        table += f"| **{metric.title()}** | {orig:.1f} | {refact:.1f} | {change} |\n"
    
    return table


def format_pr_body(
    original_pr_number: int,
    original_pr_title: str,
    score_comparison: str,
    files_refactored: List[str],
    issues_fixed: Optional[List[str]] = None
) -> str:
    """
    Format PR body with scores and file list.
    
    Args:
        original_pr_number: Original PR number
        original_pr_title: Original PR title
        score_comparison: Formatted score comparison table
        files_refactored: List of refactored filenames
        issues_fixed: List of issues fixed (optional)
        
    Returns:
        str: Markdown formatted PR body
    """
    body = f"""## Auto-Refractor Results

Refactored code from PR #{original_pr_number}: **{original_pr_title}**

{score_comparison}

### Files Refactored

"""
    
    # Add file list
    for filename in files_refactored:
        body += f"- `{filename}`\n"
    
    # Add issues fixed (if provided)
    if issues_fixed:
        body += "\n### Issues Fixed\n\n"
        for issue in issues_fixed:
            body += f"- {issue}\n"
    
    # Add footer
    body += f"""
### Links

- Original PR: [#{original_pr_number} {original_pr_title}](../pull/{original_pr_number})
- Refactoring Bot: [Auto-Refractor](https://github.com/your-repo/auto-refractor)

---

**Note:** This PR was automatically generated by Auto-Refractor bot.
Please review the changes before merging.
"""
    
    return body


async def create_refactored_pr(
    client: Githubclient,
    original_pr_number: int,
    original_pr_title: str,
    refactored_files: List[Dict[str, Any]],
    original_scores: Optional[Dict[str, float]] = None,
    refactored_scores: Optional[Dict[str, float]] = None
) -> Any:
    """
    Create PR with refactored code.
    
    Steps:
    1. Generate branch name
    2. Create branch from base
    3. Commit each refactored file
    4. Create PR with scores
    5. Add labels (future)
    
    Args:
        client: GitHub client
        original_pr_number: Original PR number
        original_pr_title: Original PR title
        refactored_files: List of dicts with {filename, content, sha}
        original_scores: Scores before refactoring (optional)
        refactored_scores: Scores after refactoring (optional)
        
    Returns:
        Created PR object
        
    Raises:
        Exception: If PR creation fails
    """
    try:
        # Step 1: Generate branch name
        branch_name = generate_branch_name(original_pr_number)
        logger.info(f"Creating branch: {branch_name}")
        
        # Step 2: Create branch from base
        try:
            client.change_branch(client.base_branch, branch_name)
            logger.info(f"Created branch {branch_name} from {client.base_branch}")
        except Exception as e:
            logger.warning(f"Branch {branch_name} might already exist: {e}")
            # Continue anyway - branch might exist from previous run
        
        # Step 3: Commit each refactored file
        commit_count = 0
        for file_data in refactored_files:
            filename = file_data.get("filename")
            content = file_data.get("content")
            sha = file_data.get("sha")
            
            if not filename or not content:
                logger.warning(f"Skipping file with missing data: {file_data}")
                continue
            
            try:
                commit_message = f"Refactor: {filename}"
                client.commit_and_push(
                    branch=branch_name,
                    path=filename,
                    content=content,
                    commit_message=commit_message,
                    sha=sha
                )
                commit_count += 1
                logger.info(f"Committed {filename} to {branch_name}")
            except Exception as e:
                logger.error(f"Failed to commit {filename}: {e}")
                continue
        
        if commit_count == 0:
            logger.error("No files were committed!")
            raise Exception("No files to create PR with")
        
        # Step 4: Format PR body
        score_comparison = format_score_comparison(original_scores, refactored_scores)
        filenames = [f.get("filename") for f in refactored_files if f.get("filename")]
        
        pr_body = format_pr_body(
            original_pr_number=original_pr_number,
            original_pr_title=original_pr_title,
            score_comparison=score_comparison,
            files_refactored=filenames
        )
        
        # Step 5: Create PR
        pr_title = f"Refactored: {original_pr_title}"
        
        logger.info(f"Creating PR: {pr_title}")
        pr = client.create_pull_request(
            branch=branch_name,
            title=pr_title,
            body=pr_body
        )
        
        logger.info(f"Successfully created PR #{pr.number}")
        return pr
        
    except Exception as e:
        logger.error(f"Failed to create refactored PR: {e}")
        raise